const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  obtenerEdificios: () => ipcRenderer.invoke('obtenerEdificios'),
  // Now operates on single field `direccion`
  agregarEdificio: (direccion) => ipcRenderer.invoke('agregarEdificio', direccion),
  buscarEdificio: (direccion) => ipcRenderer.invoke('buscarEdificio', direccion),
  eliminarEdificio: (id) => ipcRenderer.invoke('eliminarEdificio', id),
  modificarEdificio: (data) => ipcRenderer.invoke('modificarEdificio', data),
  obtenerFicha: (id) => ipcRenderer.invoke('obtenerFicha', id),
  guardarFicha: (data) => ipcRenderer.invoke('guardarFicha', data),
  // Facturas (Invoices)
  obtenerFacturas: (monthId) => ipcRenderer.invoke('obtenerFacturas', monthId),
  obtenerFacturasAll: () => ipcRenderer.invoke('obtenerFacturasAll'),
  seleccionarPDF: () => ipcRenderer.invoke('seleccionarPDF'),
  agregarFactura: (data) => ipcRenderer.invoke('agregarFactura', data),
  abrirPDF: (filePath) => ipcRenderer.invoke('abrirPDF', filePath),
  eliminarFactura: (id) => ipcRenderer.invoke('eliminarFactura', id),
  obtenerYears: (buildingId) => ipcRenderer.invoke('obtenerYears', buildingId),
  obtenerMonths: (yearId) => ipcRenderer.invoke('obtenerMonths', yearId),
  modificarFactura: (data) => ipcRenderer.invoke('modificarFactura', data),
  combinarFacturasYear: (yearId) => ipcRenderer.invoke('combinarFacturasYear', yearId),
  // Add year/month and replace PDF
  agregarYear: (data) => ipcRenderer.invoke('agregarYear', data),
  agregarMonth: (data) => ipcRenderer.invoke('agregarMonth', data),
  eliminarYear: (yearId) => ipcRenderer.invoke('eliminarYear', yearId),
  eliminarMonth: (monthId) => ipcRenderer.invoke('eliminarMonth', monthId),
  reemplazarFactura: (data) => ipcRenderer.invoke('reemplazarFactura', data),
  // Mantenimiento (Maintenance)
  agregarNotaMantenimiento: (data) => ipcRenderer.invoke('agregarNotaMantenimiento', data),
  obtenerNotasMantenimiento: (buildingId) => ipcRenderer.invoke('obtenerNotasMantenimiento', buildingId),
  eliminarNotaMantenimiento: (id) => ipcRenderer.invoke('eliminarNotaMantenimiento', id),
  cambiarEstadoMantenimiento: (id, estado) => ipcRenderer.invoke('cambiarEstadoMantenimiento', id, estado),
  // Fotos
  guardarFotoEdificio: (buildingId, file) => ipcRenderer.invoke('guardarFotoEdificio', buildingId, file),
  obtenerFotosEdificio: (buildingId) => ipcRenderer.invoke('obtenerFotosEdificio', buildingId),
  eliminarFoto: (id) => ipcRenderer.invoke('eliminarFoto', id),
  getImageSrc: (filePath) => { return 'file://' + filePath.replace(/\\/g, '/') },
  obtenerImagenBase64: (filePath) => ipcRenderer.invoke('obtenerImagenBase64', filePath),
  // Pagos
  obtenerTotalFacturado: (buildingId) => ipcRenderer.invoke('obtenerTotalFacturado', buildingId),
  obtenerTotalPagado: (buildingId) => ipcRenderer.invoke('obtenerTotalPagado', buildingId),
  obtenerEstadoPagos: (buildingId) => ipcRenderer.invoke('obtenerEstadoPagos', buildingId),
  agregarPago: (data) => ipcRenderer.invoke('agregarPago', data),
  obtenerPagos: (buildingId) => ipcRenderer.invoke('obtenerPagos', buildingId),
  eliminarPago: (pagoId) => ipcRenderer.invoke('eliminarPago', pagoId),
  obtenerEdificiosConDeuda: () => ipcRenderer.invoke('obtenerEdificiosConDeuda'),
  agregarDeuda: (data) => ipcRenderer.invoke('agregarDeuda', data),
  obtenerDeudas: (buildingId) => ipcRenderer.invoke('obtenerDeudas', buildingId),
  eliminarDeuda: (deudaId) => ipcRenderer.invoke('eliminarDeuda', deudaId),
  obtenerRutaCarpetaBackups: () => ipcRenderer.invoke('obtenerRutaCarpetaBackups'),
  obtenerBackups: () => ipcRenderer.invoke('obtenerBackups'),
  crearBackupDefault: () => ipcRenderer.invoke('crearBackupDefault'),
  seleccionarUbicacionBackup: () => ipcRenderer.invoke('seleccionarUbicacionBackup'),
  crearBackupCustom: (destino) => ipcRenderer.invoke('crearBackupCustom', destino),
  abrirCarpetaBackups: () => ipcRenderer.invoke('abrirCarpetaBackups'),
  abrirUbicacionArchivo: (filePath) => ipcRenderer.invoke('abrirUbicacionArchivo', filePath),
  extraerDatosFactura: (pdfPath) => ipcRenderer.invoke('extraer-datos-factura', pdfPath),
  combinarFacturasYearImagenes: (yearId) => ipcRenderer.invoke('combinarFacturasYearImagenes', yearId),
  editarNotaMantenimiento: (data) => ipcRenderer.invoke('editar-nota-mantenimiento', data),

  agregarItemMantenimiento: (data) => ipcRenderer.invoke('agregarItemMantenimiento', data),
  eliminarItemMantenimiento: (itemId) => ipcRenderer.invoke('eliminarItemMantenimiento', itemId),
  cambiarEstadoItemMantenimiento: (itemId, estado) => ipcRenderer.invoke('cambiarEstadoItemMantenimiento', itemId, estado),
  obtenerSeccionesMantenimiento: (id) => ipcRenderer.invoke('obtenerSeccionesMantenimiento', id),
  agregarSeccionMantenimiento: (data) => ipcRenderer.invoke('agregarSeccionMantenimiento', data),
  editarSeccionMantenimiento: (data) => ipcRenderer.invoke('editarSeccionMantenimiento', data),
  eliminarSeccionMantenimiento: (id) => ipcRenderer.invoke('eliminarSeccionMantenimiento', id),
  obtenerItemsMantenimiento: (id) => ipcRenderer.invoke('obtenerItemsMantenimiento', id),
  agregarItemMantenimiento: (data) => ipcRenderer.invoke('agregarItemMantenimiento', data),
  cambiarEstadoItemMantenimiento: (data) => ipcRenderer.invoke('cambiarEstadoItemMantenimiento', data),
  eliminarItemMantenimiento: (id) => ipcRenderer.invoke('eliminarItemMantenimiento', id),
  combinarFacturasRango: (data) => ipcRenderer.invoke('combinarFacturasRango', data),

  obtenerComprobantes: (monthId) => ipcRenderer.invoke('obtenerComprobantes', monthId),
  agregarComprobante: (data) => ipcRenderer.invoke('agregarComprobante', data),
  eliminarComprobante: (id) => ipcRenderer.invoke('eliminarComprobante', id),
})
